version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      # Regular file change events do not work properly from Windows hosts. Use more aggressive polling.
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./src/:/app/src/
      - ./public/:/app/public/
